import { Activity, ArrowRight, Bot, Boxes, CircleUserRound, ExternalLink, GitBranch, RefreshCw, Server, Users } from "lucide-react";
import type { ActivityItem } from "../activity";
import { OperationGraphReview } from "../operation-graph";
import { FeatureState, PreviewHandoff, WorkStatus } from "../shared";
import type { ProjectRoomProps, RoomMember } from "./contracts";
import { TaskBoard } from "./TaskBoard";
import "./project-room.css";
import "./room-adapter.css";

const DEFAULT_PERMISSIONS = { manageTasks: false, reviewTasks: false, reviewGraph: false, handoff: false, invite: false, comment: false };
export function ProjectRoom({ room, state = "ready", permissions = DEFAULT_PERMISSIONS, adapter, onRetryLoad, onOpenGraph, onOpenActivity, onInvite, actionError }: ProjectRoomProps) {
  if (state !== "ready" || !room) return <FeatureState state={state === "ready" ? "empty" : state} onRetry={onRetryLoad} title={state === "forbidden" ? "Project Room access restricted" : undefined} detail={actionError} />;
  return <main className="cm-room" aria-labelledby="cm-room-title"><header className="cm-room__header"><div><span className="cm-room__eyebrow">Project Room</span><h1 id="cm-room-title">{room.name}</h1>{room.context.objective ? <p>{room.context.objective}</p> : null}</div><div className="cm-room__header-actions">{onOpenActivity ? <button type="button" onClick={onOpenActivity}><Activity size={14} /> Activity</button> : null}{onOpenGraph ? <button type="button" onClick={onOpenGraph}><GitBranch size={14} /> Review graph</button> : null}</div></header>
    {actionError ? <div className="cm-room__action-error" role="alert">{actionError}</div> : null}
    {room.connectionState !== "connected" ? <div className={`cm-room__connection cm-room__connection--${room.connectionState}`} role="status"><span>{room.connectionState === "disconnected" ? "Live updates disconnected" : "Live connection not observed"}</span>{adapter?.reconnect ? <button type="button" onClick={() => void adapter.reconnect?.()}><RefreshCw size={13} /> Reload room</button> : null}</div> : null}
    <WorkStatus events={room.workEvents} connected={room.connectionState !== "disconnected"} onReconnect={room.connectionState === "disconnected" && adapter?.reconnect ? () => void adapter.reconnect?.() : undefined} />
    <div className="cm-room__context"><section><h2>Conversation context</h2><dl><div><dt>Decisions</dt><dd>{room.context.decisions.length ? <ul>{room.context.decisions.map((item) => <li key={item}>{item}</li>)}</ul> : "None recorded"}</dd></div><div><dt>Constraints</dt><dd>{room.context.constraints.length ? <ul>{room.context.constraints.map((item) => <li key={item}>{item}</li>)}</ul> : "None recorded"}</dd></div>{room.context.lastHandoff ? <div><dt>Latest handoff</dt><dd>{room.context.lastHandoff}</dd></div> : null}</dl></section>
      <section className="cm-room__runtime"><h2><Server size={14} /> Runtime health</h2>{room.deployments.length ? <ul>{room.deployments.map((item) => <li key={item.environment}><span className={`cm-health cm-health--${item.state}`} aria-label={item.state} /><strong>{item.environment}</strong><span>{item.version}</span><time>{new Date(item.checkedAt).toLocaleTimeString()}</time>{item.url ? <a href={item.url} target="_blank" rel="noreferrer" aria-label={`Open ${item.environment}`}><ExternalLink size={13} /></a> : null}</li>)}</ul> : <p>No runtime environments connected.</p>}</section></div>
    <div className="cm-room__columns"><TaskBoard tasks={room.tasks} members={room.members} canManage={permissions.manageTasks} canReview={permissions.reviewTasks} onTransition={adapter?.transitionTask ? (id, next, revision) => void adapter.transitionTask?.(id, next, revision) : undefined} onReview={adapter?.submitTaskReview ? (id, decision, note, revision) => void adapter.submitTaskReview?.(id, decision, note, revision) : undefined} /><RoomRoster members={room.members} canInvite={permissions.invite} onInvite={onInvite} /></div>
    {room.versions.length ? <PreviewHandoff versions={room.versions} members={room.members.map((member) => ({ ...member, kind: member.kind ?? "human", presence: member.presence ?? "offline" }))} selectedId={room.selectedVersionId} disabled={!permissions.handoff || !adapter?.handoffVersion} onSelect={(id) => void adapter?.selectVersion?.(id)} onHandoff={(versionId, recipientId) => void adapter?.handoffVersion?.(versionId, recipientId)} /> : null}
    <section className="cm-room__review-summary" aria-label="Review summary"><div><Boxes size={15} /><span><strong>Operation Graph</strong><small>{room.graph ? `Revision ${room.graph.revision} · ${room.graph.review.state.replace("_", " ")}` : "No revision proposed"}</small></span></div>{onOpenGraph ? <button type="button" onClick={onOpenGraph}>Open review <ArrowRight size={13} /></button> : null}</section>
    <details className="cm-room__embedded"><summary><GitBranch size={14} /> Operation Graph review</summary>{room.graph && permissions.reviewGraph && room.graph.review.state !== "approved" && adapter?.approveGraph ? <div className="cm-room__graph-approve"><span>Approve exact revision <code>{room.graph.id.slice(0, 12)}</code></span><button type="button" onClick={() => void adapter.approveGraph?.(room.graph!.id)}>Approve revision</button></div> : null}<OperationGraphReview revision={room.graph} state={room.graph ? "ready" : "empty"} canReview={false} adapter={permissions.comment && adapter?.addComment ? { addComment: adapter.addComment } : undefined} /></details>
    {room.activity ? <details className="cm-room__embedded"><summary><Users size={14} /> Durable activity</summary><RoomActivity items={room.activity} /></details> : null}
  </main>;
}

function RoomRoster({ members, canInvite, onInvite }: { members: RoomMember[]; canInvite: boolean; onInvite?: () => void }) {
  return <section className="cm-room-roster" aria-labelledby="cm-room-roster-title"><header><div><span>Durable membership</span><h2 id="cm-room-roster-title">Team</h2></div>{canInvite && onInvite ? <button type="button" onClick={onInvite}>Invite</button> : null}</header>{members.length ? <ul>{members.map((member) => <li key={member.id}>{member.kind === "agent" ? <Bot size={14} /> : <CircleUserRound size={14} />}<span><strong>{member.name}</strong><small>{member.role}</small></span>{member.presence ? <em>{member.presence}</em> : <em>Presence not reported</em>}</li>)}</ul> : <p>No members are recorded for this room.</p>}</section>;
}

function RoomActivity({ items }: { items: ActivityItem[] }) {
  return items.length ? <ol className="cm-room-activity">{items.map((item) => <li key={item.id}><span><strong>{item.title}</strong><small>{item.detail}</small></span><span><em>{item.actor}</em><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString()}</time></span></li>)}</ol> : <p className="cm-inline-empty">No durable activity has been recorded.</p>;
}
