import { Check, CircleAlert, Eye, UserRound } from "lucide-react";
import { useState } from "react";
import type { ProjectMember, ProjectTask, ReviewDecision, TaskStatus } from "../shared";
import "./project-room.css";

const STATUS_LABELS: Record<TaskStatus, string> = { todo: "To do", in_progress: "In progress", blocked: "Blocked", in_review: "In review", done: "Done" };

export function TaskBoard({ tasks, members, canManage, canReview, onUpdate, onReview }: { tasks: ProjectTask[]; members: ProjectMember[]; canManage: boolean; canReview: boolean; onUpdate?: (taskId: string, patch: Pick<ProjectTask, "status" | "ownerId">) => void; onReview?: (taskId: string, decision: ReviewDecision, note?: string) => void }) {
  const [notes, setNotes] = useState<Record<string, string>>({});
  if (!tasks.length) return <p className="cm-tasks__empty">No tasks yet. Durable assignments will appear here once work is scoped.</p>;
  return <section className="cm-tasks" aria-labelledby="cm-tasks-title"><header><div><span>Durable work queue</span><h2 id="cm-tasks-title">Tasks</h2></div><strong>{tasks.filter((task) => task.status !== "done").length} open</strong></header><ol>{tasks.map((task) => {
    const note = notes[task.id] ?? ""; const owner = members.find((member) => member.id === task.ownerId);
    return <li key={task.id} className={`cm-task cm-task--${task.status}`}><div className="cm-task__summary"><span className="cm-task__state" aria-label={STATUS_LABELS[task.status]}>{task.status === "blocked" ? <CircleAlert size={15} /> : task.status === "in_review" ? <Eye size={15} /> : <Check size={15} />}</span><div><h3>{task.title}</h3>{task.detail ? <p>{task.detail}</p> : null}<small>{owner ? `Owned by ${owner.name}` : "Unassigned"}{task.blockedBy?.length ? ` · blocked by ${task.blockedBy.join(", ")}` : ""}</small></div><span className="cm-task__review">{task.review.state.replace("_", " ")}</span></div>
      <div className="cm-task__controls" aria-label={`Controls for ${task.title}`}><label><UserRound size={12} /> Owner<select aria-label={`Owner for ${task.title}`} value={task.ownerId ?? ""} disabled={!canManage || !onUpdate} onChange={(event) => onUpdate?.(task.id, { status: task.status, ownerId: event.target.value || undefined })}><option value="">Unassigned</option>{members.map((member) => <option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>Status<select aria-label={`Status for ${task.title}`} value={task.status} disabled={!canManage || !onUpdate} onChange={(event) => onUpdate?.(task.id, { status: event.target.value as TaskStatus, ownerId: task.ownerId })}>{Object.entries(STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      {task.status === "in_review" ? <div className="cm-task__review-actions"><label htmlFor={`task-note-${task.id}`}>Review note</label><input id={`task-note-${task.id}`} value={note} onChange={(event) => setNotes((current) => ({ ...current, [task.id]: event.target.value }))} placeholder="Required for changes or rejection" disabled={!canReview} /><button type="button" disabled={!canReview || !onReview} onClick={() => onReview?.(task.id, "approved", note || undefined)}>Approve</button><button type="button" disabled={!canReview || !onReview || !note.trim()} onClick={() => onReview?.(task.id, "changes_requested", note)}>Request changes</button><button type="button" disabled={!canReview || !onReview || !note.trim()} onClick={() => onReview?.(task.id, "rejected", note)}>Reject</button></div> : null}</div>
    </li>; })}</ol></section>;
}
