import { Check, CircleAlert, Eye, UserRound } from "lucide-react";
import { useState } from "react";
import type { ReviewDecision } from "../shared";
import type { DurableTaskState, RoomMember, RoomTask } from "./contracts";
import "./project-room.css";

const STATUS_LABELS: Record<DurableTaskState, string> = { proposed: "Proposed", ready: "Ready", working: "Working", blocked: "Blocked", in_review: "In review", done: "Done", failed: "Failed", cancelled: "Cancelled" };
const TRANSITIONS: Record<DurableTaskState, DurableTaskState[]> = {
  proposed: ["ready", "cancelled"], ready: ["working", "blocked", "cancelled"], working: ["in_review", "blocked", "failed", "cancelled"],
  in_review: [], blocked: ["ready", "working", "failed", "cancelled"], failed: ["ready", "cancelled"], done: [], cancelled: [],
};

export function TaskBoard({ tasks, members, canManage, canReview, onClaim, onTransition, onReview }: { tasks: RoomTask[]; members: RoomMember[]; canManage: boolean; canReview: boolean; onClaim?: (taskId: string, expectedRevision: number) => void; onTransition?: (taskId: string, state: DurableTaskState, expectedRevision: number) => void; onReview?: (taskId: string, decision: ReviewDecision, note: string | undefined, expectedRevision: number) => void }) {
  const [notes, setNotes] = useState<Record<string, string>>({});
  const groups = [
    { id: "attention", title: "Needs attention", detail: "Human review, blockers, failures, or missing ownership", tasks: tasks.filter((task) => ["in_review", "blocked", "failed"].includes(task.durableState) || !task.ownerId) },
    { id: "active", title: "In progress", detail: "Ready or currently being worked", tasks: tasks.filter((task) => ["ready", "working"].includes(task.durableState) && task.ownerId) },
    { id: "complete", title: "Completed", detail: "Finished or intentionally cancelled", tasks: tasks.filter((task) => ["done", "cancelled"].includes(task.durableState)) },
  ].filter((group) => group.tasks.length);
  const nextAction = (task: RoomTask) => task.durableState === "in_review" ? "Human decision required" : task.durableState === "blocked" ? "Resolve the blocker" : task.durableState === "failed" ? "Review failure and retry" : !task.ownerId ? "Assign an owner" : task.durableState === "ready" ? "Ready to start" : task.durableState === "working" ? "Work in progress" : "Complete";
  return <section className="cm-tasks" aria-labelledby="cm-tasks-title"><header><div><span>WORK QUEUE</span><h2 id="cm-tasks-title">Mission tasks</h2><p>Move work from assignment to human-approved completion.</p></div><strong>{tasks.filter((task) => !["done", "cancelled"].includes(task.durableState)).length} open</strong></header>{!tasks.length ? <div className="cm-tasks__empty"><Check size={18} /><strong>No tasks yet</strong><span>Assign work from Chat or approve the Mission plan to create the queue.</span></div> : <div className="cm-task-groups">{groups.map((group) => <section key={group.id} className={`cm-task-group cm-task-group--${group.id}`}><header><div><h3>{group.title}</h3><p>{group.detail}</p></div><strong>{group.tasks.length}</strong></header><ol>{group.tasks.map((task) => {
    const note = notes[task.id] ?? ""; const owner = members.find((member) => member.id === task.ownerId); const transitions = TRANSITIONS[task.durableState];
    return <li key={task.id} className={`cm-task cm-task--${task.durableState}`}><div className="cm-task__summary"><span className="cm-task__state" aria-label={STATUS_LABELS[task.durableState]}>{task.durableState === "blocked" || task.durableState === "failed" ? <CircleAlert size={15} /> : task.durableState === "in_review" ? <Eye size={15} /> : <Check size={15} />}</span><div><div className="cm-task__title-line"><span>{STATUS_LABELS[task.durableState]}</span><small>{nextAction(task)}</small></div><h3>{task.title}</h3>{task.detail ? <p>{task.detail}</p> : null}<div className="cm-task__meta"><span><UserRound size={12} /> {owner?.name ?? "Unassigned"}</span>{task.blockedBy?.length ? <span>Blocked by {task.blockedBy.join(", ")}</span> : null}</div></div>{task.review.state !== "not_required" ? <span className="cm-task__review">{task.review.state.replace("_", " ")}</span> : null}</div>
      {!["done", "cancelled"].includes(task.durableState) ? <div className="cm-task__controls" aria-label={`Controls for ${task.title}`}>{!task.ownerId && task.durableState === "proposed" && canManage && onClaim ? <button type="button" className="primary" onClick={() => onClaim(task.id, task.revision)}>Claim ownership</button> : null}<label>Move task<select aria-label={`Move ${task.title}`} value={task.durableState} disabled={!canManage || !onTransition || transitions.length === 0} onChange={(event) => onTransition?.(task.id, event.target.value as DurableTaskState, task.revision)}><option value={task.durableState}>{STATUS_LABELS[task.durableState]}</option>{transitions.map((value) => <option key={value} value={value}>{STATUS_LABELS[value]}</option>)}</select></label>
      {task.durableState === "in_review" ? <div className="cm-task__review-actions"><label htmlFor={`task-note-${task.id}`}>Your review</label><input id={`task-note-${task.id}`} value={note} onChange={(event) => setNotes((current) => ({ ...current, [task.id]: event.target.value }))} placeholder="Add evidence or explain requested changes" disabled={!canReview} /><button type="button" className="approve" disabled={!canReview || !onReview} onClick={() => onReview?.(task.id, "approved", note || undefined, task.revision)}>Approve</button><button type="button" disabled={!canReview || !onReview || !note.trim()} onClick={() => onReview?.(task.id, "changes_requested", note, task.revision)}>Request changes</button><button type="button" disabled={!canReview || !onReview || !note.trim()} onClick={() => onReview?.(task.id, "rejected", note, task.revision)}>Reject</button></div> : null}</div> : null}
    </li>; })}</ol></section>)}</div>}</section>;
}
