{{- if .Values.disruptionBudget.enabled }}
{{- range $process := list "web" "api" "worker" }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cmul8.fullname" $ }}-{{ $process }}
  labels:
    {{- include "cmul8.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $process }}
spec:
  maxUnavailable: {{ $.Values.disruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cmul8.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $process }}
{{- end }}
{{- end }}
