apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmul8.fullname" . }}-web
  labels:
    {{- include "cmul8.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "cmul8.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
    - {name: http, port: {{ .Values.service.webPort }}, targetPort: http}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmul8.fullname" . }}-api
  labels:
    {{- include "cmul8.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "cmul8.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - {name: http, port: {{ .Values.service.apiPort }}, targetPort: http}
